// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Aliasghar Heidari",
            "email": "ali.heidari@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get list of users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "List users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetUserListSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.GetUserListFailureResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create user",
                "parameters": [
                    {
                        "description": "new user payload",
                        "name": "newUserDetails",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "user created successfully",
                        "schema": {
                            "$ref": "#/definitions/model.CreateUserSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "$ref": "#/definitions/model.CreateUserFailureResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.StatusUnauthorizedResponse"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Authenticate user and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "login success",
                        "schema": {
                            "$ref": "#/definitions/model.LoginSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "$ref": "#/definitions/model.LoginFailureResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get user by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/model.GetUserByIDSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.StatusUnauthorizedResponse"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "$ref": "#/definitions/model.StatusNotFoundResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update user by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "user payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateUserByIDRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user updated successfully",
                        "schema": {
                            "$ref": "#/definitions/model.UpdateUserByIDSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "$ref": "#/definitions/model.UpdateUserByIDFailureResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.StatusUnauthorizedResponse"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "$ref": "#/definitions/model.StatusNotFoundResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete user by ID",
                "tags": [
                    "Users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "user deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/model.DeleteUserByIDSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.StatusUnauthorizedResponse"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "$ref": "#/definitions/model.StatusNotFoundResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}/mobile-number": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Add a mobile number to user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MobileNumbers"
                ],
                "summary": "Add mobile number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "mobile number payload",
                        "name": "number",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddMobileNumberRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "mobile number added successfully",
                        "schema": {
                            "$ref": "#/definitions/model.AddMobileNumberSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "$ref": "#/definitions/model.AddMobileNumberFailureResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.StatusUnauthorizedResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}/mobile-number/{number}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a mobile number of a user",
                "tags": [
                    "MobileNumbers"
                ],
                "summary": "Delete mobile number",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "mobile number",
                        "name": "number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "mobile number deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/model.DeleteMobileNumberSuccessResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.StatusUnauthorizedResponse"
                        }
                    },
                    "404": {
                        "description": "not found",
                        "schema": {
                            "$ref": "#/definitions/model.StatusNotFoundResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AddMobileNumberFailureResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Failed to add mobile number"
                }
            }
        },
        "model.AddMobileNumberRequest": {
            "type": "object",
            "properties": {
                "mobileNumber": {
                    "$ref": "#/definitions/model.MobileNumber"
                }
            }
        },
        "model.AddMobileNumberSuccessResponse": {
            "type": "object",
            "properties": {
                "mobileNumber": {
                    "$ref": "#/definitions/model.MobileNumber"
                }
            }
        },
        "model.CreateUserFailureResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error indicates the error message",
                    "type": "string",
                    "example": "Failed to create user"
                }
            }
        },
        "model.CreateUserRequest": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "Age is the age of the user",
                    "type": "integer",
                    "example": 30
                },
                "familyName": {
                    "description": "FamilyName is the last name of the user",
                    "type": "string",
                    "example": "Doe"
                },
                "isMarried": {
                    "description": "IsMarried indicates if the user is married",
                    "type": "boolean",
                    "example": false
                },
                "name": {
                    "description": "Name is the first name of the user",
                    "type": "string",
                    "example": "John"
                }
            }
        },
        "model.CreateUserSuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message indicates the success message",
                    "type": "string",
                    "example": "User created successfully"
                },
                "user_id": {
                    "description": "UserID is the ID of the created user",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.DeleteMobileNumberSuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Mobile number deleted successfully"
                }
            }
        },
        "model.DeleteUserByIDSuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message indicates the success message",
                    "type": "string",
                    "example": "User deleted successfully"
                }
            }
        },
        "model.GetUserByIDSuccessResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "description": "User is the user object",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.User"
                        }
                    ]
                }
            }
        },
        "model.GetUserListFailureResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error indicates the error message",
                    "type": "string",
                    "example": "Failed to retrieve user list"
                }
            }
        },
        "model.GetUserListSuccessResponse": {
            "type": "object",
            "properties": {
                "users": {
                    "description": "Users is a list of users",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.User"
                    }
                }
            }
        },
        "model.LoginFailureResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error indicates the error message",
                    "type": "string",
                    "example": "Authentication failed"
                }
            }
        },
        "model.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "Password is the password of the user",
                    "type": "string",
                    "example": "1234"
                },
                "username": {
                    "description": "Username is the username of the user",
                    "type": "string",
                    "example": "Aliasghar"
                }
            }
        },
        "model.LoginSuccessResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "Token is the JWT token",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
                }
            }
        },
        "model.MobileNumber": {
            "type": "object",
            "properties": {
                "countryCode": {
                    "description": "CountryCode is the country code associated with the mobile number",
                    "type": "string"
                },
                "isActive": {
                    "description": "IsActive indicates if the mobile number is active",
                    "type": "boolean"
                },
                "number": {
                    "description": "Number is the mobile number",
                    "type": "string"
                },
                "type": {
                    "description": "Type indicates the type of mobile number (e.g., credit, debit)",
                    "type": "string"
                }
            }
        },
        "model.StatusNotFoundResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error indicates the error message",
                    "type": "string",
                    "example": "User not found"
                }
            }
        },
        "model.StatusUnauthorizedResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error indicates the error message",
                    "type": "string",
                    "example": "Authentication failed"
                }
            }
        },
        "model.UpdateUserByIDFailureResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error indicates the error message",
                    "type": "string",
                    "example": "Failed to update user"
                }
            }
        },
        "model.UpdateUserByIDRequest": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "Age is the age of the user",
                    "type": "integer",
                    "example": 21
                },
                "familyName": {
                    "description": "FamilyName is the last name of the user",
                    "type": "string",
                    "example": "Nigga"
                },
                "isMarried": {
                    "description": "IsMarried indicates if the user is married",
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "description": "Name is the first name of the user",
                    "type": "string",
                    "example": "Amir"
                }
            }
        },
        "model.UpdateUserByIDSuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message indicates the success message",
                    "type": "string",
                    "example": "User updated successfully"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "Age is the age of the user",
                    "type": "integer"
                },
                "familyName": {
                    "description": "FamilyName is the last name of the user",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier for the user",
                    "type": "integer"
                },
                "isMarried": {
                    "description": "IsMarried indicates if the user is married",
                    "type": "boolean"
                },
                "mobileNumbers": {
                    "description": "MobileNumbers is a list of mobile numbers associated with the user",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MobileNumber"
                    }
                },
                "name": {
                    "description": "Name is the first name of the user",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "security": [
        {
            "BearerAuth": []
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:9898",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Mine API - Swagger Docs",
	Description:      "API for managing users and their mobile numbers.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
